@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "io.gic.cinema.core.BookingManager",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_102337 { 
   	label=gic
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1979448766 { 
   	label=cinema
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Booking1055333420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Booking</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   chart: String[][] [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   reservationHelper: ReservationHelper [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reserve(numberOfTickets: int, booking: String[][], bookingId: String, position: int[]): String[][]</TD></TR>
<TR><TD ALIGN="LEFT" >+ confirm(bookingCopy: String[][])</TD></TR>
<TR><TD ALIGN="LEFT" >+ isBookingPresent(bookingId: String): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

   Cinema1055333420[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cinema</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   movieName: (String) [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rows: Integer [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   seatsPerRows: Integer [0..1]</TD></TR>
<HR/>

<TR><TD ALIGN="LEFT" >(C) Cinema(name: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];


BookingController1890563844[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BookingController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bookingManager: BookingManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cinema: Cinema [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- acceptBooking()</TD></TR>
<TR><TD ALIGN="LEFT" >- bookingWorkflow(cinema: Cinema, bookingManager: BookingManager)</TD></TR>
<TR><TD ALIGN="LEFT" >- checkBooking()</TD></TR>
<TR><TD ALIGN="LEFT" >- exit()</TD></TR>
<TR><TD ALIGN="LEFT" >+ start()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BookingIdGenerator832352519[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BookingIdGenerator</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   bookingCounter: Integer [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ nextBookingId(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BookingManager832352519[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BookingManager</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   booking: Booking [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   bookingIdGenerator: BookingIdGenerator [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acceptBookingDetails(numberOfTickets: Integer)</TD></TR>
<TR><TD ALIGN="LEFT" >+ isBookingPresent(bookingId: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- resolvePosition(position: String, maxRows: int): int[]</TD></TR>
<TR><TD ALIGN="LEFT" >- shallowCopyOf(booking: String[][]): String[][]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

BookingView139414012[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BookingView</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># acceptNumberOfTickets(numberOfTicketsAvailable: int): int</TD></TR>
<TR><TD ALIGN="LEFT" ># printBookings(booking: String[][], bookingId: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ChoiceView139414012[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ChoiceView</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># acceptChoice(cinemaName: String, movieName: String, numberOfSeats: int): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CinemaView139414012[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CinemaView</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># readCinemaDetails(cinemaName: String): Cinema</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ReservationHelper832352519[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ReservationHelper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ reserve(numberOfTickets: int, booking: String[][], bookingId: String, position: int[]): String[][]</TD></TR>
<TR><TD ALIGN="LEFT" >- reserveDefault(numberOfTickets: int, booking: String[][], bookingId: String, rowToStart: int): String[][]</TD></TR>
<TR><TD ALIGN="LEFT" >- reservePreferred(numberOfTickets: int, booking: String[][], bookingId: String, position: int[]): String[][]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserInterface139414012[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserInterface</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ acceptBooking(cinemaName: String, movieName: String, numberOfSeats: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ acceptChoice(cinemaName: String, movieName: String, numberOfSeats: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ acceptNumberOfTickets(numberOfTicketsAvailable: int): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserInput(message: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ printBookings(booking: String[][], bookingId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ prompt(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ promptError(message: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ readCinemaDetails(cinemaName: String): Cinema</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Booking1055333420 -> ReservationHelper832352519[label="reservationHelper[0..1]"];
BookingController1890563844 -> BookingManager832352519[label="bookingManager[0..1]"];
BookingManager832352519 -> Booking1055333420[label="booking
[0..1]"];
BookingManager832352519 -> BookingIdGenerator832352519[label="bookingIdGenerator
[0..1]"];
BookingController1890563844 -> UserInterface139414012[label="ui
[0..1]"];
UserInterface139414012 -> ChoiceView139414012[label="acceptChoice()"];
UserInterface139414012 -> CinemaView139414012[label="readCinemaDetails()"];
CinemaView139414012 -> Cinema1055333420[label="creates"]
BookingController1890563844 -> Cinema1055333420[label="uses"];
UserInterface139414012 -> BookingView139414012[label="acceptBooking()"];

}
@enduml