@startuml

digraph g {
    rankdir="LR"
    splines=polyline

'nodes 
subgraph cluster_1483722170 {
    label=BookingIdGenerator
    fillcolor="skyblue"
    labeljust=l
    style=filled
   
    BookingIdGenerator_nextBookingId[
        label="+ nextBookingId()"
        style=filled
        fillcolor=white
        tooltip="BookingIdGenerator"
        fontcolor=darkgreen
   ];
} 

subgraph cluster_1901584503 { 
   	label=Booking
	labeljust=l
	fillcolor="#a8bfb7"
	style=filled
   
    Booking_reserve[
        label="+ reserve()"
        style=filled
        fillcolor=white
        tooltip="Booking"
        fontcolor=darkgreen
    ];

    Booking_confirm[
        label="+ confirm()"
        style=filled
        fillcolor=white
        tooltip="Booking"
        fontcolor=darkgreen
    ];

    Booking_isBookingPresent[
        label="+ isBookingPresent()"
        style=filled
        fillcolor=white
        tooltip="Booking"
        fontcolor=darkgreen
    ];

    Booking_getNumberOfTicketsAvailable[
        label="+ getNumberOfTicketsAvailable()"
        style=filled
        fillcolor=white
        tooltip="Booking"
        fontcolor=darkgreen
    ];
}

subgraph cluster_1921884933 { 
   	label=BookingManager
	labeljust=l
	fillcolor="skyblue"
	style=filled

    BookingManager_acceptBookingDetails[
        label="+ acceptBookingDetails()"
        style=filled
        fillcolor=white
        tooltip="BookingManager"
        fontcolor=darkgreen
    ];

    BookingManager_isBookingPresent[
        label="+ isBookingPresent()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
    BookingManager_getNumberOfTicketsAvailable[
        label="+ getNumberOfTicketsAvailable()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
}


subgraph cluster_2054998701 { 
   	label=ReservationHelper
	labeljust=l
	fillcolor="skyblue"
	style=filled
   
    ReservationHelper_reserve[
        label="+ reserve()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
    ReservationHelper_reserveDefault[
        label="- reserveDefault()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
    ReservationHelper_reservePreferred[
        label="- reservePreferred()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

} 

subgraph cluster_802635161 {
   	label=BookingView
	labeljust=l
	fillcolor="#a89dc3"
	style=filled

    BookingView_acceptNumberOfTickets[
        label="+ acceptNumberOfTickets()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

    BookingView_printBookings[
        label="+ printBookings()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
    BookingView_printHeader[
        label="- printHeader()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

    BookingView_printBookingChart[
        label="- printBookingChart()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
    BookingView_printFooter[
        label="+ printFooter()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
}

subgraph cluster_802635162 {
   	label=ChoiceView
	labeljust=l
	fillcolor="#a89dc3"
	style=filled

    ChoiceView_acceptChoice[
        label="+ acceptChoice()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
}

subgraph cluster_802635163 {
   	label=CinemaView
	labeljust=l
	fillcolor="#a89dc3"
	style=filled

    CinemaView_acceptCinemaDetails[
        label="+ acceptCinemaDetails()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
}

subgraph cluster_802636060 { 
   	label=Console
	labeljust=l
	fillcolor="#a89dc3"
	style=filled
   
    Console_acceptChoice[
        label="+ acceptChoice()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

    Console_acceptNumberOfTickets[
        label="+ acceptNumberOfTickets()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

    Console_printBookings[
        label="+ printBookings()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];

    Console_readCinemaDetails[
        label="+ readCinemaDetails()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
} 

subgraph cluster_880359736 { 
   	label=Application
	labeljust=l
	fillcolor="#94b797"
	style=filled
   
    Application_main[
        label="+ main(String[] args)"
        style=filled
        fontcolor=darkgreen
    ];
} 

subgraph cluster_cinema {
   	label=Cinema
	labeljust=l
	fillcolor="#a8bfb7"
	style=filled

    Cinema_create[
        label="(C) cinema()"
        style=filled
        fillcolor=white
        fontcolor=darkgreen
    ];
}

subgraph cluster_913820747 { 
   	label=BookingController
	labeljust=l
	fillcolor="#eab676"
	style=filled
   
    BookingController_start[
        label="+ start()"
        style=filled
        fillcolor=white
        penwidth=3
        fontcolor=darkgreen
    ];
} 

'edges    
Application_main -> BookingController_start;
Booking_reserve -> ReservationHelper_reserve;
ReservationHelper_reserve -> ReservationHelper_reserveDefault;
ReservationHelper_reserve -> ReservationHelper_reservePreferred;
BookingController_start -> BookingManager_acceptBookingDetails;
BookingController_start -> BookingManager_isBookingPresent;
BookingController_start -> BookingManager_getNumberOfTicketsAvailable;
BookingController_start -> Console_acceptChoice;
BookingController_start -> Console_acceptNumberOfTickets;
BookingController_start -> Console_printBookings;
BookingController_start -> Console_readCinemaDetails;
Console_readCinemaDetails -> CinemaView_acceptCinemaDetails;
CinemaView_acceptCinemaDetails -> Cinema_create;
Console_acceptChoice -> ChoiceView_acceptChoice;
Console_printBookings -> BookingView_printBookings;
Console_acceptNumberOfTickets -> BookingView_acceptNumberOfTickets;
BookingView_printBookings -> BookingView_printHeader;
BookingView_printBookings -> BookingView_printBookingChart;
BookingView_printBookings -> BookingView_printFooter;
BookingManager_acceptBookingDetails -> Booking_confirm;
BookingManager_isBookingPresent -> Booking_isBookingPresent
BookingManager_getNumberOfTicketsAvailable -> Booking_getNumberOfTicketsAvailable;
BookingManager_acceptBookingDetails -> Booking_reserve;
BookingManager_acceptBookingDetails -> BookingIdGenerator_nextBookingId;

}
@enduml